//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendlyPasswordGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FriendlyPasswordGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aarão
        ///aardvark
        ///aariano
        ///aarônico
        ///aarônida
        ///aaronita
        ///ab
        ///Ab&apos;Sáber
        ///ab-henry
        ///ab-reação
        ///ab-reagir
        ///ab-reatividade
        ///ab-reativo
        ///ab-renunciar
        ///ab-reptício
        ///ab-repto
        ///ab-reticiamente
        ///ab-rogabilidade
        ///ab-rogação
        ///ab-rogar
        ///ab-rogatário
        ///ab-rogativo
        ///ab-rogatório
        ///ab-rogável
        ///ab-rompido
        ///ab-rupção
        ///ab-ruptado
        ///ab-ruptela
        ///ab-ruptinérveo
        ///ab-rupto
        ///ab-ruptude
        ///Abã
        ///Ababa
        ///ababadar
        ///ababaia
        ///ababalhar
        ///ababalhos
        ///ababalidade
        ///ababangai
        ///ababé
        ///ababelação
        ///ababelar
        ///ababelável
        ///ababil
        ///ababocado
        ///ababone
        ///ababoni
        ///ababosação
        ///ababosar
        ///ababosável
        ///ababroar
        ///aba [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string palavras {
            get {
                return ResourceManager.GetString("palavras", resourceCulture);
            }
        }
    }
}
